//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemaxEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maison
    {
        public int RefMaison { get; set; }
        public string Type { get; set; }
        public string Emplacement { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> NomreChambres { get; set; }
    }
}
