//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemaxEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int RefMessage { get; set; }
        public string Titre { get; set; }
        public string Message1 { get; set; }
        public string Date { get; set; }
        public Nullable<int> ReferAgent { get; set; }
    }
}
